mode:
  algo: DDPG #Valid Options: 'DDPG'
  type: train
# NOTE: agent_policies and eval_file are only used if [mode][type] = test
# agent_policies: ../Domains/Small_120_AGVs_SS_centralised_no_time/Results/neural_nets.csv # file containing agent policies
# eval_file: ../Domains/Small_120_AGVs_SS_centralised_no_time/Results/evaluation_29.csv # file containing best teams
domain:
  folder: ../Domains/
  warehouse: Small_SS ##Valid Opt: 'Small_SS', 'Tiny_SS'
  agents: centralized #Valid Opt: 'centralized', 'centralized_t', 'link', 'link_t', 'intersection', 'intersection_t'
graph:
  vertices:   vertices.csv
  edges:      edges.csv
  capacities: capacities.csv
DDPG:
  epochs: 1000 # set to 1 in test mode
  runs: 1
simulation:
  steps: 200
  agvs: origins_90.csv #Valid options: 90,120,200,400
  goals: goals.csv
results:
  folder:     ../Results/
  #evaluation: evaluation
  #policies:   neural_nets.csv
